[build]
  base = "react-portfolio"
  command = "npm run build"
  publish = "dist"
  publish = "public"  # This should be the directory where your static files are generated

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
