[build]
  functions = "backend/functions"  # Directory for Netlify functions

[build.environment]
  NODE_VERSION = "16"              # Specify Node.js version if needed

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true
